import type { QueryClient } from '@tanstack/react-query';

const APP_QUERY_KEYS = [
  ['operator'],
  ['stats'],
  ['skills'],
  ['tools'],
  ['augments'],
  ['media'],
  ['media-library'],
  ['courses'],
  ['courses-all'],
  ['projects'],
  ['vault-items'],
  ['ingredients-custom'],
  ['recipes'],
  ['intake-settings'],
  ['intake-logs'],
  ['sleep-sessions'],
  ['recovery-settings'],
  ['project-obj-counts'],
  ['tool-progress'],
  ['augment-progress'],
  ['class'],
  ['xp-recent'],
  ['quick-log-templates'],
  ['tool-session-counts'],
  ['tool-last-session'],
  ['skill-session-counts'],
  ['skill-last-session'],
  ['augment-session-counts'],
  ['augment-last-session'],
  ['checkins-heatmap'],
  ['checkin-today'],
  ['habits'],
  ['habit-logs-today'],
  ['arsenal-counts'],
  ['sessions-all'],
  ['skill-sessions'],
  ['tool-sessions'],
  ['augment-sessions'],
  ['project-sessions'],
  ['notes'],
  ['course'],
  ['course-sections'],
  ['terminal-skills-list'],
  ['terminal-tools-list'],
  ['terminal-augments-list'],
  ['terminal-projects-list'],
  ['terminal-notes-list'],
  ['terminal-media-list'],
  ['terminal-habits-list'],
  ['terminal-courses-list'],
  ['terminal-vault-list'],
  ['terminal-recipes-list'],
  ['terminal-resources-list'],
  ['terminal-ingredients-list'],
  ['activity-by-stat'],
];

export async function refreshAppData(queryClient: QueryClient) {
  await Promise.all(
    APP_QUERY_KEYS.map((queryKey) => queryClient.invalidateQueries({ queryKey }))
  );
  // Note: invalidateQueries already triggers refetches on active subscribers.
  // The explicit refetchQueries call was redundant and caused a second wave of fetches.
}
