// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxeltoxalykylgtcokcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4ZWx0b3hhbHlreWxndGNva2N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4NDg2MDUsImV4cCI6MjA4ODQyNDYwNX0.G15ORwnxmaoqdjknzhYbMN4dgUq7BuhLuG69LuDyuN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});